### PR TITLE
tests: add more delete range test cases

### PR DESCRIPTION
**Pull request by choleraehyq**
PTAL @siddontang @zhangjinpeng1987 
Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

### CODE REVIEW

**Comment by siddontang** [comment]
should add more cases, like:

db1 [a, b)
db2 [a, c)
delete range db2 [a,c)
ingest db1 [a, b) to db2

**Comment by siddontang** [comment]
db1 [a, b), [b, c)
db2 [a, b), [b, c)
delete db2 [b, c)
ingest db1 [b, c) to db2
check db1 [a, b), db2 [a, b)

**Comment by siddontang** [comment]
delete range
ingest sst
compact range
check

**Comment by choleraehyq** [comment]
@siddontang Done.

**Comment by siddontang** [comment]
LGTM
PTAL @zhangjinpeng1987

**Pull request merged**
