### PR TITLE
use pingcap/5.7.3 rocksdb

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
1) support sse
2) Fix missing BYTES_PER_WRITE for pipeline write

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
Can it still work when link to the official release dynamically?

**Comment by huachaohuang** [comment]
This version contains a modification of `DeleteFilesInRange` (https://github.com/pingcap/rocksdb/commit/4ca006c6b34f6a4f31d3e52bd7abaf9c4e9f6c53), should we remove that commit from this branch?

**Comment by zhangjinpeng1987** [comment]
@huachaohuang done.

**Pull request merged**
