### PR TITLE
base compaction threads

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
@siddontang @lishihai9017 PTAL

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@hhkbp2 PTAL

**Comment by zhangjinpeng1987** [comment]
@lishihai9017 PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by lishihai9017** [comment]
LGTM

**Comment by siddontang** [comment]
Please fix the conflict. 
@zhangjinpeng1987

**Pull request merged**
