### PR TITLE
Update to latest Titan

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Including the following Titan changes:
7f8e787cf 2019-05-02 yiwu@pingcap.com     Titan: fix crash on recover when obsolete file exists 
fe4c735cb 2019-05-01 xy.tao@outlook.com   Titan: Fix iterator retrying and add seek related test 
be63a4930 2019-05-01 xy.tao@outlook.com   Titan: Add unit test for error handling 
9d876a029 2019-04-30 zbk602423539@gmail.. clean unused field 
c287e97c2 2019-04-29 yiwu@pingcap.com     Titan: Add blob file header
4e68c178f 2019-04-28 zbk602423539@gmail.. Titan: Remove superversion dependency 
39d392a90 2019-04-22 yiwu@pingcap.com     Titan: Remove DBOptions::orignal_table_factory
04ef84338 2019-04-19 james_199@126.com    Titan: Add IngestExternalFiles test 
47e1ff5b8 2019-04-19 james_199@126.com    Titan: remove DropColumnFamily override 
10c97f235 2019-04-18 james_199@126.com    Titan: Add ReadAfterDropCF test 

Signed-off-by: Yi Wu <yiwu@pingcap.com>

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
CI failed, please check.

**Comment by Connor1996** [comment]
Oh, seems that I didn't clean it up. I will fix it.

**Comment by yiwu-arbug** [comment]
Not ready to merge. Need to include https://github.com/pingcap/rocksdb/pull/93 as well.

**Comment by yiwu-arbug** [comment]
The PR is ready now.

**Comment by yiwu-arbug** [comment]
Closing in favor of #293

**Pull request closed without merging**
