### PR TITLE
Add bytes_per_sync and wal_bytes_per_sync options

### PR DESCRIPTION
**Pull request by arthurprs**
Add bytes_per_sync and wal_bytes_per_sync

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @zhangjinpeng1987

**Comment by ngaut** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
@arthurprs  redefined crocksdb_options_set_bytes_per_sync error.

**Comment by arthurprs** [comment]
@zhangjinpeng1987 what do you mean? Did I forget to add an error?

**Comment by arthurprs** [comment]
Ahh I see it now, I'm sorry :/
I'm surprised that CI was green though.

**Comment by siddontang** [comment]
@arthurprs 

The CI doesn't run the tests now, we will add it later.  You can also run `make test` on your local computer then send the PR.

**Pull request merged**
