### PR TITLE
build: disable jemalloc

### PR DESCRIPTION
**Pull request by BusyJay**
Makefile will link to jemalloc automatically if it's installed on the system. But this may lead to unexpected build failure if installed jemalloc is outdated. Actually rustc will link to built-in jemalloc automatically, hence we can just skip it when building native library.

### CODE REVIEW

**Comment by siddontang** [comment]
PTAL @andelf

**Comment by siddontang** [comment]
LGTM

**Comment by andelf** [comment]
Any idea to prove static rocksdb with `DISABLE_JEMALLOC` will use jemalloc when linked with rust?

**Comment by BusyJay** [comment]
You can use gdb to run the built binary, and set a breakpoint to any where allocation happen, then step by step, you should see jemalloc is invoked.

**Comment by andelf** [comment]
LGTM

**Pull request merged**
