### PR TITLE
get histogram detail

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Get histogram detail from rocksdb's statistics.
@siddontang @BusyJay PTAL

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@hhkbp2 @disksing PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
@BusyJay PTAL

**Comment by hhkbp2** [comment]
LGTM

**Pull request merged**
