### PR TITLE
build: check rocksdb version when compiling

### PR DESCRIPTION
**Pull request by BusyJay**
Add version check so that we can know exactly what's going wrong instead of a bunch of declaration error.

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by siddontang** [comment]
@BusyJay 

Can we check it in the build script because we have already put the version information here?

**Comment by BusyJay** [comment]
Build script is just used for static link, which will be hardly ever broken. The check is primary for dynamic linking. We may remove the script after cmake is introduced.

**Pull request merged**
