### PR TITLE
impl Sync & Send for DBRateLimiter

### PR DESCRIPTION
**Pull request by UncP**
fix issue https://github.com/pingcap/tikv/issues/2598

### CODE REVIEW

**Comment by BusyJay** [comment]
I don't think it's going to work. Raw pointers are neither sync nor send, it has nothing to do with `DBRateLimiter` itself.

**Comment by UncP** [comment]
So is this the problem of the compiler, regarding that issue?

**Comment by BusyJay** [comment]
Can you reproduce the issue? You can't control raw pointers, but you can control the struct that use raw pointers.

**Comment by UncP** [comment]
I tried with the same rust version, the compilation is fine on my machine.

**Pull request closed without merging**
