### PR TITLE
support pre-generate bindings for aarch64

### PR DESCRIPTION
**Pull request by glorv**
in #402 we already support pre-generate bindings for x64_64, this pr add support for aarch64

Signed-off-by: glorv glorvs@163.com

### CODE REVIEW

**Comment by Connor1996** [comment]
Sorry, we have no plan to pre-generate bindings for aarch64. It's fine for generating it when building.

**Comment by glorv** [comment]
> Sorry, we have no plan to pre-generate bindings for aarch64. It's fine for generating it when building.

From v4.0, we need to support aarch64 platform, so it's make sense to use pre-generated bindings to make compilation easily. In cenos7 with aarch64 cpu, the raw bind-gen need newer version of clang (>6) which isn't provided in most case. So I think we should support this feature.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
@yiwu-arbug PTAL

**Review by overvenus — APPROVED** [review]
Thanks!

**Pull request merged**
