### PR TITLE
SstFileWriter: get the ownership of Options

### PR DESCRIPTION
**Pull request by choleraehyq**
@zhangjinpeng1987 PTAL

Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

### CODE REVIEW

**Comment by siddontang** [comment]
any resonse to move the option here?

**Comment by zhangjinpeng1987** [comment]
Please use rustfmt(0.6.0) to format the code.

**Comment by siddontang** [comment]
LGTM

**Comment by choleraehyq** [comment]
CI will passed after @follitude update the md5sum hash of rocksdb 5.5.1.

**Comment by choleraehyq** [comment]
@zhangjinpeng1987 Finally CI passed, can this be merged?

**Pull request merged**
