### PR TITLE
Update rate_limiter api

### PR DESCRIPTION
**Pull request by UncP**
Signed-off-by: UncP <uncp.xu@gmail.com>

The rust-rocksdb::RateLimiter does not have to be mutable, because rocksdb::RateLimiter inside is already mutable.

Created this pr to fix TiKV compilation error.

### CODE REVIEW

**Comment by siddontang** [comment]
@UncP 

You can use `Arc<RwLock<RateLimiter>>` outside directly, it is the common use for Rust.

**Comment by UncP** [comment]
Isn't this too expensive? It needs locking.

**Comment by UncP** [comment]
I think we need to update this, if not, `Arc<RwLock<RateLimiter>>` won't work either.

**Comment by siddontang** [comment]
Is RocksDB RateLimter already thread-safe? If yes, we don't need to lock outside. 

PTAL @huachaohuang @zhangjinpeng1987

**Comment by UncP** [comment]
It is thread safe, there is a mutex locked when we call rate-limiter api.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
